name: Performance Tests (Gatling + Taurus)

on:
  workflow_dispatch:
    inputs:
      simulation:
        description: 'Gatling simulation class (FQN)'
        required: true
        default: 'simulations.BasicSimulation'

jobs:
  gatling-taurus:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Install Taurus
        run: |
          python3 -m pip install bzt

      - name: Build Gatling fat JAR
        run: |
          cd gatling
          mvn clean package -DskipTests

      - name: Verify simulation inside shaded JAR
        run: |
          cd gatling
          JAR=$(ls target/*-shaded.jar)
          echo "Using JAR: $JAR"
          jar tf "$JAR" | grep simulations/BasicSimulation.class




      - name: Run Taurus
        run: |
          cd gatling
          bzt taurus-gatling.yml \
            -o scenarios.mi-simulacion.simulation=${{ github.event.inputs.simulation }}

      - name: Upload Taurus Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gatling-taurus-report
          path: |
            gatling/target/gatling/
            gatling/*/gatling-results.xml
            gatling/bzt.log
